import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class GreatLeagueAllService {

  greatLeaguePokemonArray = [{
    name: 'Bulbasaur',
    hp: 113,
    atk:105.1,
    def: 99.5,
    numberOfMOves: 4,
    type: 'grass',
    type2: 'poison',
    moves: ['Seed Bomb','Power Whip','Return','Sludge Bomb'],
  },
    {
      name: 'Ivysaur',
      hp: 132,
      atk:118,
      def: 121.9,
      numberOfMOves: 4,
      type: 'grass',
      type2: 'poison',
       moves: ['Solar Beam','Power Whip','Return','Sludge Bomb'],
    },
    {
      name: 'Venusaur',
      hp: 123,
      atk:121.2,
      def: 124.2,
      numberOfMOves: 4,
      type: 'grass',
      type2: 'poison',
      moves: ['Petal Blizzard','Sludge Bomb','Solar Beam','Frenzy Plant'],
    },
    {
      name: 'Charmander',
      hp: 105,
      atk:103.5,
      def: 85.3,
      numberOfMOves: 3,
      type: 'fire',
      type2: '',
      moves: ['Flamethrower','Flame Charge','Flame Burst'],
    },
    {
      name: 'Charmeleon',
      hp: 131,
      atk:124.8,
      def: 109.8,
      numberOfMOves: 3,
      type: 'fire',
      type2: '',
      moves: ['Fire Punch','Flamethrower','Flame Burst'],
    },
    {
      name: 'Charizard',
      hp: 117,
      atk:131.5,
      def: 110.8,
      numberOfMOves: 5,
      type: 'fire',
      type2: 'dragon',
      moves: ['Blast Burn','Dragon Claw','Fire Blast','Flamethrower','Overheat'],
    },
    {
      name: 'Squirtle',
      hp: 112,
      atk:86.1,
      def: 107.4,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Aqua Tail','Aqua Jet','Water Pulse'],
    },
    {
      name: 'Wartortle',
      hp: 132,
      atk:111.4,
      def: 134.3,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Hydro Pump','Aqua Jet','Ice Beam'],
    },
    {
      name: 'Blastoise',
      hp: 130,
      atk:110.1,
      def: 142.2,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Hydro Pump','Aqua Jet','Ice Beam'],
    },
    {
      name: 'Caterpie',
      hp: 113,
      atk:55.3,
      def: 55.3,
      numberOfMOves: 2,
      type: 'bug',
      type2: '',
      moves: ['Bug Bite','Tackle'],
    },
    {
      name: 'Metapod',
      hp: 120,
      atk:47.4,
      def: 120,
      numberOfMOves: 2,
      type: 'bug',
      type2: '',
      moves: ['Bug Bite','Tackle'],
    },
    {
      name: 'Butterfree',
      hp: 127,
      atk:125.2,
      def: 112.4,
      numberOfMOves: 3,
      type: 'bug',
      type2: 'flying',
      moves: ['Bug Buzz','Signal Beam','Psychic'],
    },
    {
      name: 'Weedle',
      hp: 106,
      atk:61.3,
      def: 51.3,
      numberOfMOves: 1,
      type: 'bug',
      type2: 'poison',
      moves: ['Struggle'],
    },
    {
      name: 'Kakuna',
      hp: 113,
      atk:48.2,
      def: 71.1,
      numberOfMOves: 1,
      type: 'bug',
      type2: 'poison',
      moves: ['Struggle'],
    },
    {
      name: 'Beedrill',
      hp: 132,
      atk:126.2,
      def: 106.7,
      numberOfMOves: 5,
      type: 'bug',
      type2: 'poison',
      moves: ['Arial Ace','Drill Run','Fell Stinger','Sludge Bomb','X-Scissor'],
    },
    {
      name: 'Pidgey',
      hp: 106,
      atk:79,
      def: 69.5,
      numberOfMOves: 3,
      type: 'normal',
      type2: 'flying',
      moves: ['Arial Ace','Air Cutter','Twister'],
    },
    {
      name: 'Pidgeotto',
      hp: 138,
      atk:104.3,
      def: 94.8,
      numberOfMOves: 3,
      type: 'normal',
      type2: 'flying',
      moves: ['Arial Ace','Air Cutter','Twister'],
    },
    {
      name: 'Pidgeot',
      hp: 145,
      atk:115.2,
      def: 116.6,
      numberOfMOves: 4,
      type: 'normal',
      type2: 'flying',
      moves: ['Arial Ace','Air Cutter','Brave bird','Hurricane'],
    },
    {
      name: 'Rattata',
      hp: 92,
      atk:93.2,
      def: 67.1,
      numberOfMOves: 3,
      type: 'normal',
      type2: '',
      moves: ['Body Slam','Dig','Hyper Fang'],
    },
    {
      name: 'Raticate',
      hp: 124,
      atk:124,
      def: 117.8,
      numberOfMOves: 3,
      type: 'normal',
      type2: '',
      moves: ['Hyper Beam','Dig','Hyper Fang'],
    },
    {
      name: 'Fearow',
      hp: 126,
      atk:129.7,
      def: 105.5,
      numberOfMOves: 4,
      type: 'normal',
      type2: 'flying',
      moves: ['Arial Ace','Drill Run','Sky Attack','Twister'],
    },
    {
      name: 'Spearow',
      hp: 106,
      atk:100.3,
      def: 59.2,
      numberOfMOves: 4,
      type: 'normal',
      type2: 'flying',
      moves: ['Arial Ace','Drill Peck','Sky Attack','Twister'],
    },
    {
      name: 'Ekans',
      hp: 99,
      atk:98.7,
      def: 88.5,
      numberOfMOves: 4,
      type: 'poison',
      type2: '',
      moves: ['Poison Fang','Gunk shot','Sludge Bomb','Wrap'],
    },
    {
      name: 'Arbok',
      hp: 124,
      atk:122.7,
      def: 120.4,
      numberOfMOves: 4,
      type: 'poison',
      type2: '',
      moves: ['Acid Spray','Dark Pulse','Gunk Shot','Sludge Wave'],
    },
    {
      name: 'Pikachu',
      hp: 99,
      atk:100.3,
      def: 87.7,
      numberOfMOves: 5,
      type: 'electric',
      type2: '',
      moves: ['Disharge','Surf','Thunder','Thunderbolt','Wild Charge'],
    },
    {
      name: 'Raichu',
      hp: 115,
      atk:131.4,
      def: 113,
      numberOfMOves: 5,
      type: 'electric',
      type2: '',
      moves: ['Brick Break','Skull Bash','Thunder','Thunder Punch','Wild Charge'],
    },
    {
      name: 'Sandshrew',
      hp: 120,
      atk:111.4,
      def: 106.6,
      numberOfMOves: 4,
      type: 'ground',
      type2: '',
      moves: ['Rock Slide','Dig','Rock Tomb','Sand Tomb'],
    },
    {
      name: 'Sandslash',
      hp: 128,
      atk:119.1,
      def: 123.6,
      numberOfMOves: 3,
      type: 'ground',
      type2: '',
      moves: ['Bulldoze','Earthquake','Rock Tomb'],
    },
    {
      name: 'Nidoran-f',
      hp: 127,
      atk:79.8,
      def: 82.1,
      numberOfMOves: 3,
      type: 'poison',
      type2: '',
      moves: ['Body Slam','Poison Fang','Sludge Bomb'],
    },
    {
      name: 'Nidorina',
      hp: 147,
      atk:104.3,
      def: 106.6,
      numberOfMOves: 3,
      type: 'poison',
      type2: '',
      moves: ['Dig','Poison Fang','Sludge Bomb'],
    },
    {
      name: 'Nidoqueen',
      hp: 140,
      atk:115.3,
      def: 120.4,
      numberOfMOves: 4,
      type: 'poison',
      type2: 'ground',
      moves: ['Earthquake','Earth Power','Sludge Wave','Stone Edge'],
    },
    {
      name: 'Nidoran-m',
      hp: 114,
      atk:94.8,
      def: 71.9,
      numberOfMOves: 3,
      type: 'poison',
      type2: '',
      moves: ['Body Slam','Horn Attack','Sludge Bomb'],
    },
    {
      name: 'Nidorino',
      hp: 135,
      atk:120.1,
      def: 99.5,
      numberOfMOves: 3,
      type: 'poison',
      type2: '',
      moves: ['Dig','Horn Attack','Sludge Bomb'],
    },
    {
      name: 'Nidoking',
      hp: 129,
      atk:127.8,
      def: 106.5,
      numberOfMOves: 4,
      type: 'poison',
      type2: 'ground',
      moves: ['Earthquake','Earthpower','Megahorn','Sludge Wave'],
    },
    {
      name: 'Clefairy',
      hp: 147,
      atk:96.4,
      def: 97.2,
      numberOfMOves: 4,
      type: 'fairy',
      type2: '',
      moves: ['Body Slam','Disarming Voice','Moon Blast'],
    },
    {
      name: 'Clefable',
      hp: 143,
      atk:117.2,
      def: 112.7,
      numberOfMOves: 4,
      type: 'fairy',
      type2: '',
      moves: ['Dazzlim Gleam','Meteor Mash','Moon Blast','Psychic'],
    },
    {
      name: 'Vulpix',
      hp: 103,
      atk:87.7,
      def: 97.9,
      numberOfMOves: 3,
      type: 'fire',
      type2: '',
      moves: ['Body Slam','Flamethrower','Moon Blast','Flame Charge'],
    },
    {
      name: 'Ninetales',
      hp: 128,
      atk:112.8,
      def: 136.9,
      numberOfMOves: 6,
      type: 'fire',
      type2: '',
      moves: ['Fire Blast','Flamethrower','Heat Wave','Overheat','Psyshock','Solar Beam'],
    },
    {
      name: 'jigglypuff',
      hp: 210,
      atk:75,
      def: 44.2,
      numberOfMOves: 5,
      type: 'normal',
      type2: 'fairy',
      moves: ['Body Slam','Dazzling Gleam','Disarming Voice','Gyro Ball','play Rough'],
    },
    {
      name: 'Wigglytuff',
      hp: 224,
      atk:114.1,
      def: 76.8,
      numberOfMOves: 4,
      type: 'normal',
      type2: 'fairy',
      moves: ['Dazzling Gleam','ice Beam','Hyper Beam','play Rough'],
    },
    {
      name: 'Zubat',
      hp: 106,
      atk:77.4,
      def: 69.5,
      numberOfMOves: 4,
      type: 'poison',
      type2: 'flying',
      moves: ['Air cutter','Poison Fang','Sludge Bomb','Swift'],
    },
    {
      name: 'Golbat',
      hp: 141,
      atk:115.8,
      def: 118.7,
      numberOfMOves: 4,
      type: 'poison',
      type2: 'flying',
      moves: ['Air cutter','Poison Fang','Ominous Wind','Shadow Ball'],
    },
    {
      name: 'Oddish',
      hp: 141,
      atk:115.8,
      def: 118.7,
      numberOfMOves: 3,
      type: 'grass',
      type2: 'poison',
      moves: ['Moonblast','Seed Bomb','Sludge Bomb'],
    },
    {
      name: 'Gloom',
      hp: 133,
      atk:116.5,
      def: 120.4,
      numberOfMOves: 3,
      type: 'grass',
      type2: 'poison',
      moves: ['Moonblast','Petal Blizzard','Sludge Bomb'],
    },
    {
      name: 'Vileplume',
      hp: 122,
      atk:126.5,
      def: 114,
      numberOfMOves: 4,
      type: 'grass',
      type2: 'poison',
      moves: ['Moonblast','Petal Blizzard','Sludge Bomb','Solar Beam'],
    },
    {
      name: 'Paras',
      hp: 99,
      atk:107.4,
      def: 90,
      numberOfMOves: 3,
      type: 'grass',
      type2: 'bug',
      moves: ['Cross Poison','Seed Bomb','X-scissor'],
    },
    {
      name: 'Parasect',
      hp: 126,
      atk:122.7,
      def: 118.2,
      numberOfMOves: 3,
      type: 'grass',
      type2: 'bug',
      moves: ['Cross Poison','Solar Beam','X-scissor'],
    },
    {
      name: 'Venonat',
      hp: 134,
      atk:90.8,
      def: 90.8,
      numberOfMOves: 3,
      type: 'poison',
      type2: 'bug',
      moves: ['Poison Fang','Psybeam','Siganl Beam'],
    },
    {
      name: 'Venomoth',
      hp: 131,
      atk:125.3,
      def: 109.2,
      numberOfMOves: 4,
      type: 'poison',
      type2: 'bug',
      moves: ['PoisonFang','Bug Buzz','Psychic','Silver Wind'],
    },
    {
      name: 'Diglett',
      hp: 64,
      atk:97.9,
      def: 73.4,
      numberOfMOves: 3,
      type: 'ground',
      type2: '',
      moves: ['Dig','Mud Bomb','Rock Tomb'],
    },
    {
      name: 'Dugtrio',
      hp: 99,
      atk:137.5,
      def: 119.3,
      numberOfMOves: 3,
      type: 'ground',
      type2: '',
      moves: ['Earthquake','Mud Bomb','Stone Edge'],
    },
    {
      name: 'Meowth',
      hp: 106,
      atk:84.5,
      def: 73.4,
      numberOfMOves: 4,
      type: 'normal',
      type2: '',
      moves: ['Body Slam','Dark Pulse','Foul Play','Night Slash'],
    },
    {
      name: 'Persian',
      hp: 138,
      atk:117.6,
      def: 117.6,
      numberOfMOves: 3,
      type: 'normal',
      type2: '',
      moves: ['Play Rough','power Gem','Foul Play','Night Slash'],
    },
    {
      name: 'Psyduck',
      hp: 120,
      atk:108.2,
      def: 86.9,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Aqual Tail','Cross Chop','PsyBeam'],
    },
    {
      name: 'Golduck',
      hp: 132,
      atk:123.6,
      def: 111.3,
      numberOfMOves: 6,
      type: 'water',
      type2: '',
      moves: ['Bubble Beam','Cross Chop','Hydro Pump','Ice Beam','Psychic','Synchronoise'],
    },
    {
      name: 'Mankey',
      hp: 106,
      atk:128.8,
      def: 76.6,
      numberOfMOves: 3,
      type: 'fighting',
      type2: '',
      moves: ['Brick Break','Cross Chop','Low Sweep'],
    },
    {
      name: 'Primeape',
      hp: 117,
      atk:137.5,
      def: 101.1,
      numberOfMOves: 3,
      type: 'fighting',
      type2: '',
      moves: ['close Combat','Cross Chop','Low Sweep','Night Slash'],
    },
    {
      name: 'Growlithe',
      hp: 127,
      atk:119.3,
      def: 85.3,
      numberOfMOves: 3,
      type: 'fire',
      type2: '',
      moves: ['Body Slam','Flametrower','Flame Wheel'],
    },
    {
      name: 'Arcanine',
      hp: 127,
      atk:130.4,
      def: 103.4,
      numberOfMOves: 5,
      type: 'fire',
      type2: '',
      moves: ['Bulldoze','Crunch','Fire Blast','Flamethrower','Wild Charge'],
    },
    {
      name: 'Poliwag',
      hp: 106,
      atk:91.6,
      def: 76.6,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Body Slam','Bubble Beam','Mud Bomb'],
    },
    {
      name: 'PoliWrath',
      hp: 139,
      atk:114,
      def: 124,
      numberOfMOves: 5,
      type: 'water',
      type2: 'fighting',
      moves: ['Dinamic Punch','Hydro Pump','ice Punch','Power-Up Punch','Submission'],
    },
    {
      name: 'Abra',
      hp: 85,
      atk:165.9,
      def: 76.6,
      numberOfMOves: 4,
      type: 'psychic',
      type2: '',
      moves: ['Psyshock','Shadow Ball','ice Punch','Siganl Beam'],
    },
    {
      name: 'Kadabra',
      hp: 93,
      atk:162,
      def: 91.6,
      numberOfMOves: 3,
      type: 'psychic',
      type2: '',
      moves: ['Dazzling Gleam','Psybeam','Shadow Ball'],
    },
    {
      name: 'Alakazam',
      hp: 91,
      atk:154.1,
      def: 103.1,
      numberOfMOves: 6,
      type: 'psychic',
      type2: '',
      moves: ['Dazzling Gleam','Fire Punch','focus Blast','Future Sight','Psychic','Shadow Ball'],
    },
    {
      name: 'Machop',
      hp: 147,
      atk:120.1,
      def: 76.6,
      numberOfMOves: 3,
      type: 'fighting',
      type2: '',
      moves: ['Brick Break','Cross Chop','Low Sweep'],
    },
    {
      name: 'Machoke',
      hp: 144,
      atk:125.1,
      def: 98.9,
      numberOfMOves: 4,
      type: 'fighting',
      type2: '',
      moves: ['Brick Break','Cross Chop','Dinamic Punch','Submission'],
    },
    {
      name: 'Machamp',
      hp: 125,
      atk:134.4,
      def: 99.4,
      numberOfMOves: 7,
      type: 'fighting',
      type2: '',
      moves: ['Close Combat','Cross Chop','Dinamic Punch','Submission','Heavy Slam','Rock Slide','Stone Edge'],
    },
    {
      name: 'Bellsprout',
      hp: 120,
      atk:121.7,
      def: 60,
      numberOfMOves: 3,
      type: 'grass',
      type2: 'poison',
      moves: ['Power Whip','Sludge Bomb','Wrap'],
    },
    {
      name: 'Weepinbell',
      hp: 140,
      atk:137.5,
      def: 84.5,
      numberOfMOves: 3,
      type: 'grass',
      type2: 'poison',
      moves: ['Power Whip','Seed Bomb','Sludge Bomb'],
    },
    {
      name: 'Victreebel',
      hp: 131,
      atk:96,
      def: 133.2,
      numberOfMOves: 5,
      type: 'grass',
      type2: 'poison',
      moves: ['Acid Spray','Leaf Blade','Leaf Tornado','Sludge Bomb','Solar Beam'],
    },
    {
      name: 'Tentacool',
      hp: 106,
      atk:88.5,
      def: 129.6,
      numberOfMOves: 3,
      type: 'water',
      type2: 'poison',
      moves: ['Bubble Beam','Water Pulse','Wrap'],
    },
    {
      name: 'Tentacruel',
      hp: 132,
      atk:108.1,
      def: 145,
      numberOfMOves: 4,
      type: 'water',
      type2: 'poison',
      moves: ['Acid Spray','Blizzard','Hydro Pump','Sludge Wave'],
    },
    {
      name: 'Geodude',
      hp: 106 ,
      atk:116.1,
      def: 116.1,
      numberOfMOves: 2,
      type: 'rock',
      type2: 'ground',
      moves: ['Rock Trow','Tackle'],
    },
    {
      name: 'Graveler',
      hp: 118 ,
      atk:120.4,
      def: 130.7,
      numberOfMOves: 4,
      type: 'rock',
      type2: 'ground',
      moves: ['Rock Blast','Dig','Rock Slide','Stone Edge'],
    },
    {
      name: 'Golem',
      hp: 119 ,
      atk:123.4,
      def: 123.4,
      numberOfMOves: 4,
      type: 'rock',
      type2: 'ground',
      moves: ['Ancient Power','Earthquake','Rock Blast','Stone Edge'],
    },
    {
      name: 'Ponyta',
      hp: 117 ,
      atk:131.9,
      def: 110.2,
      numberOfMOves: 4,
      type: 'fire',
      type2: '',
      moves: ['Fire Blast','Flame Charge','Flame Wheel','Stomp'],
    },
    {
      name: 'Rapidash',
      hp: 114,
      atk:132.6,
      def: 112.1,
      numberOfMOves: 3,
      type: 'fire',
      type2: '',
      moves: ['Drill Run','Fire Blast','Heat Wave'],
    },
    {
      name: 'Slowpoke',
      hp: 175,
      atk:97.9,
      def: 89.3,
      numberOfMOves: 3,
      type: 'water',
      type2: 'psychic',
      moves: ['Psychic','Psyshock','Water Pulse'],
    },
    {
      name: 'Slowbro',
      hp:146,
      atk:112.1,
      def: 122.2,
      numberOfMOves: 3,
      type: 'water',
      type2: 'psychic',
      moves: ['Ice Beam','psychic','Water Pulse'],
    },
    {
      name: 'Magnemite',
      hp:85,
      atk:142.2,
      def: 107.4,
      numberOfMOves: 3,
      type: 'electric',
      type2: 'steel',
      moves: ['Disharge','Magnet Bomb','Thunderbolt'],
    },
    {
      name: 'Magneton',
      hp:96,
      atk:141.3,
      def: 116.5,
      numberOfMOves: 4,
      type: 'electric',
      type2: 'steel',
      moves: ['Disharge','Flash Cannon','Magnet Bomb','Zap Cannon'],
    },
    {
      name: 'Farfetchd',
      hp: 123,
      atk:109.8,
      def: 102.7,
      numberOfMOves: 3,
      type: 'normal',
      type2: 'flying',
      moves: ['Arial Ace','Air Cutter','leaf Blade'],
    },
    {
      name: 'Dodrio',
      hp: 111 ,
      atk:142.6,
      def: 99.4,
      numberOfMOves: 4,
      type: 'normal',
      type2: 'flying',
      moves: ['Arial Ace','Air Cutter','Brave bird','Drill Neck'],
    },
    {
      name: 'Doduo',
      hp: 99 ,
      atk:136.7,
      def: 77.4,
      numberOfMOves: 4,
      type: 'normal',
      type2: 'flying',
      moves: ['Arial Ace','Swift','Brave bird','Drill Neck'],
    },
    {
      name: 'Seel',
      hp: 140 ,
      atk:79,
      def: 107.4,
      numberOfMOves: 4,
      type: 'water',
      type2: '',
      moves: ['Aqual Jet','Aqua Tail','Aurora Beam','ice Wind'],
    },
    {
      name: 'Dewgong',
      hp: 161 ,
      atk:100.8,
      def: 137.1,
      numberOfMOves: 5,
      type: 'water',
      type2: 'ice',
      moves: ['Aqual Jet','Blizzard','Aurora Beam','ice Wind','Water Pulse'],
    },
    {
      name: 'Grimmer',
      hp: 162,
      atk:118.5,
      def: 82.9,
      numberOfMOves: 3,
      type: 'poison',
      type2: '',
      moves: ['Mud Bomb','Sludge','Sludge Bomb'],
    },
    {
      name: 'Muk',
      hp: 149,
      atk:114.9,
      def: 113.1,
      numberOfMOves: 5,
      type: 'poison',
      type2: '',
      moves: ['Acid Spray','Dark Pulse','Gunk Shot','Sludge Wave','Thunder Punch'],
    },
    {
      name: 'Shellder',
      hp: 92,
      atk:103.5,
      def: 117.7,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Bubble Beam','Ice Wind','Water pulse'],
    },
    {
      name: 'Cloyster',
      hp:95 ,
      atk:117.8,
      def: 170.4,
      numberOfMOves: 5,
      type: 'water',
      type2: 'ice',
      moves: ['Aurora Beam','Avalanche','Blizzard','Hydro Pump','Ice Wind'],
    },
    {
      name: 'Gastly',
      hp: 92,
      atk:158.8,
      def: 64.8,
      numberOfMOves: 4,
      type: 'ghost',
      type2: 'poison',
      moves: ['Dark Pulse','Night Shade','Ominuos Wind','Sludge Bomb'],
    },
    {
      name: 'Haunter',
      hp: 101,
      atk:159.7,
      def: 87,
      numberOfMOves: 4,
      type: 'ghost',
      type2: 'poison',
      moves: ['Dark Pulse','Shadow Ball','Shadow Punch','Sludge Bomb'],
    },
    {
      name: 'Gengar',
      hp: 99,
      atk:153.9,
      def: 95.5,
      numberOfMOves: 6,
      type: 'ghost',
      type2: 'poison',
      moves: ['Dark Pulse','Focus Blast','Psychic','Sludge Bomb','Shadow Ball','Sludge Wave'],
    },
    {
      name: 'Onix',
      hp: 99,
      atk:79,
      def: 195.2,
      numberOfMOves: 5,
      type: 'rock',
      type2: 'ground',
      moves: ['Heavy Slam','Iron Head','Rock Slide','Sand Bomb','Stone Edge'],
    },
    {
      name: 'Drowzee',
      hp: 134,
      atk:82.1,
      def: 119.3,
      numberOfMOves: 3,
      type: 'psychic',
      type2: '',
      moves: ['Psybeam','Psychic','Psyshock'],
    },
    {
      name: 'Hypno',
      hp: 149,
      atk:101.7,
      def: 145,
      numberOfMOves: 8,
      type: 'psychic',
      type2: '',
      moves: ['Fire Punch','Psychic','Psyshock','Focus Blast','Future Sight','Ice Punch','Shadow Ball','Thunder Punch'],
    },
    {
      name: 'Krabby',
      hp:92 ,
      atk:148.5,
      def: 109.8,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Bubble Beam','Vise Grip','Water Pulse'],
    },
    {
      name: 'Kingler',
      hp:96,
      atk:143.3,
      def: 113.5,
      numberOfMOves: 4,
      type: 'water',
      type2: '',
      moves: ['Crabhammer','Vise Grip','Water Pulse','X-Scissor'],
    },
    {
      name: 'Voltorb',
      hp:106,
      atk:97.9,
      def: 99.5,
      numberOfMOves: 4,
      type: 'eletric',
      type2: '',
      moves: ['Disharge','Gyro Ball','Signal Beam','Thunderbolt'],
    }, {
      name: 'Electrode',
      hp:118,
      atk:120.7,
      def: 130.4,
      numberOfMOves: 4,
      type: 'eletric',
      type2: '',
      moves: ['Disharge','Foul Play','hyper Beam','Thunderbolt'],
    },
    {
      name: 'Exeggcute',
      hp:134,
      atk:96.4,
      def: 110.6,
      numberOfMOves: 3,
      type: 'grass',
      type2: 'psychic',
      moves: ['Ancient Power','Psychic','Seed Bomb'],
    },
    {
      name: 'Exeggutor',
      hp:132,
      atk:134.4,
      def: 94.2,
      numberOfMOves: 3,
      type: 'grass',
      type2: 'psychic',
      moves: ['Solar Beam','Psychic','Seed Bomb'],
    },
    {
      name: 'Hitmonlee',
      hp:94,
      atk:139.9,
      def: 121.4,
      numberOfMOves: 5,
      type: 'fighting',
      type2: '',
      moves: ['brick Break','Close Combat','Low Sweep','Stomp', 'Stone Edge'],
    },
    {
      name: 'Hitmonchan',
      hp:100,
      atk:127.6,
      def: 137.5,
      numberOfMOves: 6,
      type: 'fighting',
      type2: '',
      moves: ['Brick Break','Close Combat','Fire Punch','Ice Punch','Power-Up Punch', 'Thunder Punch'],
    },

    {
      name: 'lickitung',
      hp:175,
      atk:97.2,
      def: 120.1,
      numberOfMOves: 4,
      type: 'normal',
      type2: '',
      moves: ['Body Slam','Hyper Beam','Power Whip','Stomp'],
    },
    {
      name: 'Koffing',
      hp:106,
      atk:105.9,
      def: 123.2,
      numberOfMOves: 3,
      type: 'poison',
      type2: '',
      moves: ['Dark Pulse','Sludge','Sludge Bomb'],
    },
    {
      name: 'Weezing',
      hp:118,
      atk:116.2,
      def: 140.9,
      numberOfMOves: 3,
      type: 'poison',
      type2: '',
      moves: ['Dark Pulse','Shadow Baal','Sludge Bomb','ThunderBolt'],
    },
    {
      name: 'Ryhorn',
      hp:161,
      atk:111.4,
      def: 112.2,
      numberOfMOves: 3,
      type: 'ground',
      type2: 'rock',
      moves: ['Bulldoze','Horn Attack','Stomp'],
    },
    {
      name: 'Ryhdon',
      hp:138,
      atk:125.1,
      def: 103.9,
      numberOfMOves: 3,
      type: 'ground',
      type2: 'rock',
      moves: ['Stone','Earthquake','Megahorn'],
    },
    {
      name: 'Tangela',
      hp:120,
      atk:123.4,
      def: 122.7,
      numberOfMOves: 4,
      type: 'grass',
      type2: '',
      moves: ['Grass Knot','power Whip','Sludge Bomb','Solar Beam'],
    },
    {
      name: 'Kangaskhan',
      hp: 155,
      atk:113.4,
      def: 112.1,
      numberOfMOves: 6,
      type: 'normal',
      type2: '',
      moves: ['brick Break','Crunch','Earthquake','outrage','Power-Up Punch','Stomp'],
    },
    {
      name: 'Horsea',
      hp: 92,
      atk:113.8,
      def: 93.2,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Bubble Beam','Dragon Pulse','Flash Cannon'],
    },
    {
      name: 'Kingdra',
      hp: 119,
      atk:122.4,
      def: 124.2,
      numberOfMOves: 4,
      type: 'water',
      type2: 'dragon',
      moves: ['Blizzard','Hydro Pump','Octakooka','Outrage'],
    },
    {
      name: 'Goldeen',
      hp: 113,
      atk:109,
      def: 98.7,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Aqual Tail','Horn Attack','Water Pulse'],
    },
    {
      name: 'Seaking',
      hp: 140,
      atk:120.3,
      def: 110.7,
      numberOfMOves: 5,
      type: 'water',
      type2: '',
      moves: ['Drill Run','Ice Beam','Ice Wind','Megahorn','Water Pulse'],
    },
    {
      name: 'Starmie',
      hp: 104,
      atk: 131.5,
      def: 124.6,
      numberOfMOves: 5,
      type: 'water',
      type2: 'psychic',
      moves: ['Hydro Pump','Ice Beam','Power Gem','Psychic','Thunder'],
    },
    {
      name: 'Staryu',
      hp: 92,
      atk: 120.1,
      def: 100.3,
      numberOfMOves: 3,
      type: 'water',
      type2: '',
      moves: ['Bubble Beam','Swift','Power Gem'],
    },
    {
      name: 'Mr.Mime',
      hp: 91,
      atk: 129.5,
      def: 147,
      numberOfMOves: 3,
      type: 'pshychic',
      type2: 'fairy',
      moves: ['Psybeam','Psychic','Shadow Ball'],
    },
    {
      name: 'Scyther',
      hp: 112,
      atk: 133.4,
      def: 112.6,
      numberOfMOves: 3,
      type: 'bug',
      type2: 'flying',
      moves: ['Psybeam','Psychic','Shadow Ball'],
    },










  ];





  constructor() { }
}
